sudo: required
services:
  - docker

before_install:
  - docker build -t nortolanavb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nortolanavb/docker-react yarn test

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-east-2-754600573887"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"